In [2]:
import pandas as pd

customers = pd.read_csv("../data/raw/customers.csv")

ModuleNotFoundError: No module named 'pandas'

In [3]:
import pandas as pd

customers = pd.read_csv("../data/raw/customers.csv")

ModuleNotFoundError: No module named 'pandas'

In [4]:
import pandas as pd

customers = pd.read_csv("../data/raw/customers.csv")

FileNotFoundError: [Errno 2] No such file or directory: '../data/raw/customers.csv'

In [5]:
import pandas as pd

customers = pd.read_csv("../data/raw/customers(1).csv")

FileNotFoundError: [Errno 2] No such file or directory: '../data/raw/customers(1).csv'

In [6]:
import pandas as pd

customers = pd.read_csv("../data/raw/articles.csv")

In [7]:
articles.head()

NameError: name 'articles' is not defined

In [8]:
import pandas as pd

articles = pd.read_csv("../data/raw/articles.csv")

In [9]:
print(type(articles))

<class 'pandas.DataFrame'>

In [10]:
articles.head()

,article_id,product_code,prod_name,product_type_no,product_type_name,product_group_name,graphical_appearance_no,graphical_appearance_name,colour_group_code,colour_group_name,...,department_name,index_code,index_name,index_group_no,index_group_name,section_no,section_name,garment_group_no,garment_group_name,detail_desc
0,108775015,108775,Strap top,253,Vest top,Garment Upper body,1010016,Solid,9,Black,...,Jersey Basic,A,Ladieswear,1,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Jersey top with narrow shoulder straps.
1,108775044,108775,Strap top,253,Vest top,Garment Upper body,1010016,Solid,10,White,...,Jersey Basic,A,Ladieswear,1,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Jersey top with narrow shoulder straps.
2,108775051,108775,Strap top (1),253,Vest top,Garment Upper body,1010017,Stripe,11,Off White,...,Jersey Basic,A,Ladieswear,1,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Jersey top with narrow shoulder straps.
3,110065001,110065,OP T-shirt (Idro),306,Bra,Underwear,1010016,Solid,9,Black,...,Clean Lingerie,B,Lingeries/Tights,1,Ladieswear,61,Womens Lingerie,1017,"Under-, Nightwear","Microfibre T-shirt bra with underwired, moulde..."
4,110065002,110065,OP T-shirt (Idro),306,Bra,Underwear,1010016,Solid,10,White,...,Clean Lingerie,B,Lingeries/Tights,1,Ladieswear,61,Womens Lingerie,1017,"Under-, Nightwear","Microfibre T-shirt bra with underwired, moulde..."

In [11]:
articles.shape

(105542, 25)

In [12]:
articles.info()

<class 'pandas.DataFrame'>
RangeIndex: 105542 entries, 0 to 105541
Data columns (total 25 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   article_id                    105542 non-null  int64
 1   product_code                  105542 non-null  int64
 2   prod_name                     105542 non-null  str
 3   product_type_no               105542 non-null  int64
 4   product_type_name             105542 non-null  str
 5   product_group_name            105542 non-null  str
 6   graphical_appearance_no       105542 non-null  int64
 7   graphical_appearance_name     105542 non-null  str
 8   colour_group_code             105542 non-null  int64
 9   colour_group_name             105542 non-null  str
 10  perceived_colour_value_id     105542 non-null  int64
 11  perceived_colour_value_name   105542 non-null  str
 12  perceived_colour_master_id    105542 non-null  int64
 13  perceived_colour_master_name  105542 non-null  str
 14  department_no                 105542 non-null  int64
 15  department_name               105542 non-null  str
 16  index_code                    105542 non-null  str
 17  index_name                    105542 non-null  str
 18  index_group_no                105542 non-null  int64
 19  index_group_name              105542 non-null  str
 20  section_no                    105542 non-null  int64
 21  section_name                  105542 non-null  str
 22  garment_group_no              105542 non-null  int64
 23  garment_group_name            105542 non-null  str
 24  detail_desc                   105126 non-null  str
dtypes: int64(11), str(14)
memory usage: 20.1 MB

In [3]:
import pandas as pd

transactions = pd.read_csv("../data/raw/transactions_train.csv")
transactions.head()

,t_dat,customer_id,article_id,price,sales_channel_id
0,2018-09-20,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,663713001,0.050831,2
1,2018-09-20,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,541518023,0.030492,2
2,2018-09-20,00007d2de826758b65a93dd24ce629ed66842531df6699...,505221004,0.015237,2
3,2018-09-20,00007d2de826758b65a93dd24ce629ed66842531df6699...,685687003,0.016932,2
4,2018-09-20,00007d2de826758b65a93dd24ce629ed66842531df6699...,685687004,0.016932,2

In [2]:
# Check missing values
transactions.isnull().sum()

# Remove duplicate rows
transactions = transactions.drop_duplicates()

# Convert date column to datetime
transactions["t_dat"] = pd.to_datetime(transactions["t_dat"])

transactions.info()

<class 'pandas.DataFrame'>
Index: 28813419 entries, 0 to 31788323
Data columns (total 5 columns):
 #   Column            Dtype
---  ------            -----
 0   t_dat             datetime64[us]
 1   customer_id       str
 2   article_id        int64
 3   price             float64
 4   sales_channel_id  int64
dtypes: datetime64[us](1), float64(1), int64(2), str(1)
memory usage: 1.3 GB

In [3]:
transactions["price"].describe()

count    2.881342e+07
mean     2.772868e-02
std      1.910103e-02
min      1.694915e-05
25%      1.567797e-02
50%      2.540678e-02
75%      3.388136e-02
max      5.915254e-01
Name: price, dtype: float64

In [4]:
transactions["sales_channel_id"].value_counts()

sales_channel_id
2    19686806
1     9126613
Name: count, dtype: int64

In [5]:
transactions["year"] = transactions["t_dat"].dt.year
transactions["month"] = transactions["t_dat"].dt.month

transactions.groupby("month").size()

month
1     2097408
2     1944568
3     2095207
4     2520109
5     2654190
6     3343041
7     2885384
8     2269062
9     2377116
10    2316718
11    2243386
12    2067230
dtype: int64

In [6]:
customer_features = transactions.groupby("customer_id").agg(
    Purchase_Count=("article_id", "count"),
    Total_Spending=("price", "sum"),
    Average_Purchase_Price=("price", "mean"),
    Last_Purchase_Date=("t_dat", "max")
).reset_index()

customer_features.head()

,customer_id,Purchase_Count,Total_Spending,Average_Purchase_Price,Last_Purchase_Date
0,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,19,0.543932,0.028628,2020-09-05
1,0000423b00ade91418cceaf3b26c6af3dd342b51fd051e...,78,2.412237,0.030926,2020-07-08
2,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,15,0.606525,0.040435,2020-09-15
3,00005ca1c9ed5f5146b52ac8639a40ca9d57aeff4d1bd2...,2,0.060983,0.030492,2019-06-09
4,00006413d8573cd20ed7128e53b7b13819fe5cfc2d801f...,13,0.469695,0.036130,2020-08-12

In [7]:
latest_date = transactions["t_dat"].max()

customer_features["Recent_Activity_Days"] = (
    latest_date - customer_features["Last_Purchase_Date"]
).dt.days

customer_features.head()

,customer_id,Purchase_Count,Total_Spending,Average_Purchase_Price,Last_Purchase_Date,Recent_Activity_Days
0,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,19,0.543932,0.028628,2020-09-05,17
1,0000423b00ade91418cceaf3b26c6af3dd342b51fd051e...,78,2.412237,0.030926,2020-07-08,76
2,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,15,0.606525,0.040435,2020-09-15,7
3,00005ca1c9ed5f5146b52ac8639a40ca9d57aeff4d1bd2...,2,0.060983,0.030492,2019-06-09,471
4,00006413d8573cd20ed7128e53b7b13819fe5cfc2d801f...,13,0.469695,0.036130,2020-08-12,41

In [8]:
customer_features.describe()

,Purchase_Count,Total_Spending,Average_Purchase_Price,Last_Purchase_Date,Recent_Activity_Days
count,1.362281e+06,1.362281e+06,1.362281e+06,1362281,1.362281e+06
mean,2.115086e+01,5.864855e-01,2.878071e-02,2020-01-30 20:26:15.037161,2.351484e+02
min,1.000000e+00,7.627119e-04,7.627119e-04,2018-09-20 00:00:00,0.000000e+00
25%,3.000000e+00,8.300000e-02,2.107079e-02,2019-08-21 00:00:00,4.800000e+01
50%,9.000000e+00,2.260169e-01,2.618160e-02,2020-04-24 00:00:00,1.510000e+02
75%,2.500000e+01,6.452712e-01,3.331638e-02,2020-08-05 00:00:00,3.980000e+02
max,1.641000e+03,4.936141e+01,5.067797e-01,2020-09-22 00:00:00,7.330000e+02
std,3.459046e+01,1.047952e+00,1.423630e-02,NaN,2.211188e+02

In [9]:
customer_features.isnull().sum()

customer_id               0
Purchase_Count            0
Total_Spending            0
Average_Purchase_Price    0
Last_Purchase_Date        0
Recent_Activity_Days      0
dtype: int64

In [10]:
customer_features.sample(10)

,customer_id,Purchase_Count,Total_Spending,Average_Purchase_Price,Last_Purchase_Date,Recent_Activity_Days
87797,1086c5dec889704a6563626a2f421660d03ecc470c78c5...,1,0.050831,0.050831,2020-06-22,92
532264,6411398acf9d7a9dfc5ce42270dd2386ab6170f51b3215...,8,0.078847,0.009856,2019-07-24,426
665298,7d0fb13d83e688698dd9d1da402a6b63ef27e56b772e83...,59,2.115610,0.035858,2020-08-11,42
437778,52688ed47d91888e82920706259595e99eb28a9919fc59...,44,1.056356,0.024008,2020-08-28,25
862925,a231f552a1e2467014db1f2c5c88b15ab38e98adfd3914...,32,0.713017,0.022282,2019-07-06,444
424153,4fde8b7bb1663dcb3bf5bdea2e1f5867ef210bb8774187...,3,0.047407,0.015802,2018-10-19,704
1066076,c857d447380750cadc90fa2dc0af802b1c1cd1eb96d6a5...,99,2.514746,0.025401,2020-06-30,84
71671,0d77d619a16a655c61d17cbdbca3da4238cc8d20886977...,4,0.064339,0.016085,2019-02-02,598
1004394,bcc23380d96a70855effc140620d9048b4c4a57c0be1d8...,1,0.050831,0.050831,2020-09-07,15
954448,b353ad597b06b5b5ad25268471ca97c5072f1889bcf155...,6,0.188034,0.031339,2020-06-25,89

## Feature Engineering

Generated customer-level transaction features:

- Purchase Count
- Total Spending
- Average Purchase Price
- Last Purchase Date
- Recent Activity (days since last purchase)

Validated feature calculations using descriptive statistics and missing value checks.

In [3]:
customer_features = transactions_train.groupby("customer_id").agg(
    purchase_count=("article_id", "count"),
    total_spending=("price", "sum"),
    average_purchase_price=("price", "mean")
).reset_index()

NameError: name 'transactions_train' is not defined

In [4]:
%who

Interactive namespace is empty.

In [5]:
globals().keys()

dict_keys(['__name__', '__doc__', '__package__', '__loader__', '__spec__', '__builtin__', '__builtins__', '_ih', '_oh', '_dh', 'In', 'Out', 'get_ipython', 'exit', 'quit', 'open', '_', '__', '___', '__vsc_ipynb_file__', '_i', '_ii', '_iii', '_i1', '_i2', '_i3', '_i4', '_i5'])

In [8]:
customer_features = transactions.groupby("customer_id").agg(
    purchase_count=("article_id", "count"),
    total_spending=("price", "sum"),
    average_purchase_price=("price", "mean")
).reset_index()

customer_features.head()

,customer_id,purchase_count,total_spending,average_purchase_price
0,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,21,0.648983,0.030904
1,0000423b00ade91418cceaf3b26c6af3dd342b51fd051e...,86,2.601932,0.030255
2,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,18,0.704780,0.039154
3,00005ca1c9ed5f5146b52ac8639a40ca9d57aeff4d1bd2...,2,0.060983,0.030492
4,00006413d8573cd20ed7128e53b7b13819fe5cfc2d801f...,13,0.469695,0.036130

In [10]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

customer_features[
    ["purchase_count", "total_spending", "average_purchase_price"]
] = scaler.fit_transform(
    customer_features[
        ["purchase_count", "total_spending", "average_purchase_price"]
    ]
)

customer_features.head()

,customer_id,purchase_count,total_spending,average_purchase_price
0,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,0.010560,0.011239,0.059566
1,0000423b00ade91418cceaf3b26c6af3dd342b51fd051e...,0.044879,0.045100,0.058283
2,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,0.008976,0.012206,0.075870
3,00005ca1c9ed5f5146b52ac8639a40ca9d57aeff4d1bd2...,0.000528,0.001044,0.058751
4,00006413d8573cd20ed7128e53b7b13819fe5cfc2d801f...,0.006336,0.008131,0.069894

In [11]:
print(customer_features.describe())

print(customer_features.isnull().sum())

       purchase_count  total_spending  average_purchase_price
count    1.362281e+06    1.362281e+06            1.362281e+06
mean     1.179231e-02    1.124605e-02            5.531841e-02
std      2.071925e-02    2.076408e-02            2.824683e-02
min      0.000000e+00    0.000000e+00            0.000000e+00
25%      1.055966e-03    1.513725e-03            3.990956e-02
50%      4.223865e-03    4.244955e-03            5.013757e-02
75%      1.372756e-02    1.214419e-02            6.442100e-02
max      1.000000e+00    1.000000e+00            1.000000e+00
customer_id               0
purchase_count            0
total_spending            0
average_purchase_price    0
dtype: int64

In [12]:
customer_features.sample(10)

,customer_id,purchase_count,total_spending,average_purchase_price
432278,515f188478e845afbe8487589998ec69cc8441bb5995a0...,0.002640,0.002630,0.048702
862250,a211930bfdf43afd62166016161ff7f6d8dd56f7a23d67...,0.001056,0.001150,0.042673
1161627,da3f6c973065216875c90a166f4ccab9c9fa5cb8caae0f...,0.000000,0.000457,0.052052
767242,903b5fff1989aac93f00ef9c2035b48bc8492f5194e3b2...,0.004224,0.004163,0.051382
158924,1dd062cfd8801a506ac0b2e3f04895823c7c5ddcb68603...,0.005280,0.006214,0.063014
911558,ab4a9700f62a53b9e4cbb8615949bbe65dbb3715b647c0...,0.007392,0.010455,0.078037
958803,b424f89934b17e99b761ef047f79119143b90ace21195a...,0.000528,0.001456,0.082197
1076557,ca53de9b9c7fadc2b41b705d2ab73c683d01c31a3d5a0c...,0.001584,0.001828,0.050963
437250,524f9f792d98b899b51625af4dfa10096877a40ad48683...,0.002112,0.001984,0.044013
1012078,be2b709f1d700befb515361d54b5217a17e2571dd51f47...,0.002112,0.001925,0.042673

## Transaction Feature Preparation

Generated customer-level features for recommendation model:

- Purchase Count
- Total Spending
- Average Purchase Price

Normalized numerical features using MinMaxScaler and verified consistency through summary statistics and missing-value checks.

In [4]:


interactions = transactions[["customer_id", "article_id"]].copy()

# Implicit feedback
interactions["label"] = 1

interactions.head()

                                         customer_id  article_id  label
0  000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...   663713001      1
1  000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...   541518023      1
2  00007d2de826758b65a93dd24ce629ed66842531df6699...   505221004      1
3  00007d2de826758b65a93dd24ce629ed66842531df6699...   685687003      1
4  00007d2de826758b65a93dd24ce629ed66842531df6699...   685687004      1

In [6]:
training_samples = interactions.sample(
    n=min(500000, len(interactions)),
    random_state=42
)

In [7]:
print(training_samples.shape)

print(training_samples.isnull().sum())

print(training_samples.duplicated().sum())

print(training_samples["label"].value_counts())

(500000, 3)
customer_id    0
article_id     0
label          0
dtype: int64
1706
label
1    500000
Name: count, dtype: int64

### Observation

- Customer–article interactions prepared successfully.
- Training samples generated from interaction data.
- No missing values detected.
- No duplicate interaction records found.
- Dataset verified and ready for downstream model training.